//Code by Briann, last updated on December 15th, 2022
//v1.1

document.write('<html><center>');
document.write('<style>');
document.write('html, body ');
document.write('{ ');
document.write(' overflow: hidden');
document.write('}');
document.write('');
document.write('#ex {');
document.write('	color: #1d6e15;');
document.write('	text-align: center;');
document.write('	text-decoration: none;');
document.write('	display: inline-block;');
document.write('	font-size: 16px;');
document.write('	cursor: pointer;');
document.write('	font-weight: bold;');
document.write('	border-radius: 10px;');
document.write('	background: #7AEB8D;');
document.write('	padding: 10px 13px;');
document.write('	border: 0.5px solid #7AEB8D;');
document.write('	transition: 0.3s;');
document.write('	font-family: arial;');
document.write('}');
document.write('');
document.write('#ex:hover {');
document.write('	color: white;');
document.write('	background-color: #2EA11B;');
document.write('}');
document.write('');
document.write('#code {');
document.write('	width: 60%;');
document.write('	height: 100%;');
document.write('	padding: 20px;');
document.write('	float: left;');
document.write('	background:#34495E;');
document.write('}');
document.write('');
document.write('#console {');
document.write('	width: 40%;');
document.write('	height: 100%;');
document.write('	padding: 20px;');
document.write('	float: left;');
document.write('	background:#000;');
document.write('}');
document.write('');
document.write('#boxes {');
document.write('	width: 50%;');
document.write('	height: 50%;');
document.write('  overflow: auto;');
document.write('	padding:0;');
document.write('  margin:0;');
document.write('}');
document.write('');
document.write('textarea {color:#fff; resize: none;}');
document.write('</style>');
document.write('');
document.write('	<a id="ex" onclick="runEval()"><svg preserveAspectRatio="xMidYMin" width="16" height="16" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="currentColor" class="jsx-1319342727 " style="vertical-align: middle;"><path d="M20.2253 11.5642C20.5651 11.7554 20.5651 12.2446 20.2253 12.4358L5.74513 20.5809C5.41183 20.7683 5 20.5275 5 20.1451L5 3.85492C5 3.47251 5.41183 3.23165 5.74513 3.41914L20.2253 11.5642Z" stroke-width="2"></path></svg> Execute</a><br><br>');
document.write('');
document.write('	<div id="boxes">');
document.write('	<textarea id="code" spellcheck="false" placeholder="//Enter code here.."></textarea>');
document.write('	<textarea id="console" spellcheck="false" placeholder="Waiting for output..." disabled=""></textarea>');
document.write('<script>');
document.write('	function runEval() {');
document.write('		try {');
document.write('			eval(document.getElementById(\'code\').value)');
document.write('');
document.write('			if(document.getElementById(\'console\').value != "") {');
document.write('				document.getElementById(\'console\').value += `\\nCode ran successfully!`;');
document.write('			}else{');
document.write('				document.getElementById(\'console\').value += `Code ran successfully!`;');
document.write('			}');
document.write('		} catch (e) {');
document.write('			if(document.getElementById(\'console\').value != "") {');
document.write('				document.getElementById(\'console\').value += `\\nError: ${e.message}`;');
document.write('			}else{');
document.write('				document.getElementById(\'console\').value += `Error: ${e.message}`;');
document.write('			}');
document.write('		}');
document.write('	}');
document.write('</script>');
document.write('	</div>');
document.write('</center></html>');
